[package]
name = "kist-chunker"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
kist-format.workspace = true

fastcdc.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
rand.workspace = true
